set(GcodeProcessorLibSources ${GcodeProcessorLibSources}
    array_list.h
    circular_buffer.h
    extruder.cpp
    extruder.h
    gcode_comment_processor.cpp
    gcode_comment_processor.h
    gcode_parser.cpp
    gcode_parser.h
    gcode_position.cpp
    gcode_position.h
    logger.cpp
    logger.h
    parsed_command.cpp
    parsed_command.h
    parsed_command_parameter.cpp
    parsed_command_parameter.h
    position.cpp
    position.h
    utilities.cpp
    utilities.h
    fpconv.h
    fpconv.cpp
    version.generated.h
    version.h
)