set(ArcWelderInverseProcessorSources ${ArcWelderInverseProcessorSources}
    arc_interpolation.h
    arc_interpolation.cpp
    arc_interpolation_structs.h
    ArcWelderInverseProcessor.h
    ArcWelderInverseProcessor.cpp
    firmware.cpp
    firmware.h
    firmware_types.h
    marlin_1.cpp
    marlin_1.h
    marlin_2.cpp
    marlin_2.h
    prusa.cpp
    prusa.h
    repetier.cpp
    repetier.h
    smoothieware.cpp
    smoothieware.h
)